#!/usr/bin/env python3
"""Write a GLM 5 setup file (.sam) out as an espgensam ``groups:`` YAML file.

    tools/sam2yaml.py "Home Cinema.sam" --monitors 1842915,1654321,1987654 \
        -o gensam_groups.yaml

Then include the result from the hub configuration::

    gensam:
      groups: !include gensam_groups.yaml

Most setups do not need this: point the hub straight at the setup file instead and the same
conversion happens while the configuration is validated, with nothing to regenerate::

    gensam:
      sam_file: "~/Documents/Genelec/GLM5/Setup Files/Home Cinema.sam"

This tool is the YAML-emitting front end over ``components/gensam/sam_import.py``, which does
the reading and the mapping and documents both. It is worth keeping for seeing exactly what a
setup file converts to, for diffing two GLM exports, and as the escape hatch when a file needs
hand-repair before the component will accept it.

Needs PyYAML, which ESPHome already depends on. If your system interpreter lacks it,
either ``pip install pyyaml`` or run this with ESPHome's own interpreter.
"""

import argparse
import logging
import os
import sys

# The mapping lives with the component, because an external component fetched from git gets
# only that directory and needs it at validation time. Putting the component's own directory
# on the path (rather than components/) imports it as a plain top-level module, so nothing
# here loads components/gensam/__init__.py and with it the whole of ESPHome.
sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "components", "gensam")
)

import sam_import  # noqa: E402

try:
    import yaml
except ImportError:  # pragma: no cover - environment problem, not a code path
    sys.exit(
        "error: this tool needs PyYAML.\n"
        "       pip install pyyaml\n"
        "       (ESPHome already depends on it, so running this with ESPHome's own\n"
        "        interpreter also works if you would rather not install it globally.)"
    )


class _Flow(dict):
    """A mapping to emit inline, as ``{a: 1, b: 2}``.

    Only the filter bands use it. A device carries twenty of them, so block style would turn
    a three-group setup into roughly eight hundred lines of four-line stanzas; inline they
    stay one line each and the bank can be read at a glance.
    """


def _represent_flow(dumper, data):
    return dumper.represent_mapping("tag:yaml.org,2002:map", data, flow_style=True)


yaml.add_representer(_Flow, _represent_flow, Dumper=yaml.SafeDumper)


def _document(groups):
    """Build the plain data structure that gets dumped.

    The shape is sam_import's, unchanged -- it is the same shape the component validates -- so
    the only thing added here is presentation: the bands are re-wrapped for flow style.
    """
    doc = sam_import.to_group_config(groups)
    for group in doc:
        for dev in group["devices"]:
            dev["filters"] = [_Flow(band) for band in dev["filters"]]
    return doc


def emit_yaml(groups, source_path):
    header = (
        f"# Generated by tools/sam2yaml.py from {source_path}\n"
        f"#\n"
        f"# Include from the hub configuration with:  groups: !include <this file>\n"
        f"# Regenerate rather than editing if the GLM setup changes.\n\n"
    )
    body = yaml.safe_dump(
        _document(groups),
        sort_keys=False,      # field order is meaningful to a reader; alphabetical is not
        default_flow_style=False,
        width=1000,           # never wrap a band across lines
        allow_unicode=True,   # group names come from a free text field
    )
    return header + body


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("sam", help="GLM 5 setup file to convert")
    ap.add_argument(
        "--monitors",
        help="comma-separated unique_ids to keep, matching the hub's monitors: block. "
        "Without it every device in the file is emitted, including any GLM has retained "
        "but you do not own.",
    )
    ap.add_argument("-o", "--output", help="write here instead of stdout")
    args = ap.parse_args(argv)

    # sam_import reports what it cannot carry across through logging, so that the component's
    # warnings land in the ESPHome validation log. Here they go back to being stderr lines.
    logging.basicConfig(level=logging.WARNING, format="warning: %(message)s", stream=sys.stderr)

    known = None
    if args.monitors:
        try:
            known = {int(m.strip()) for m in args.monitors.split(",") if m.strip()}
        except ValueError:
            ap.error("--monitors takes the decimal unique_ids from your monitors: block")

    try:
        model = sam_import.parse_sam(args.sam)
        groups = sam_import.convert(model, known)
    except sam_import.SamError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1

    if not groups:
        print("error: no convertible groups found", file=sys.stderr)
        return 1

    text = emit_yaml(groups, args.sam)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(text)
        counts = ", ".join(f"{g['name']!r} ({len(g['devices'])})" for g in groups)
        print(f"wrote {args.output}: {counts}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
